### ISSUE TITLE
MW - Anpassungen für Aufnahme in CSALT

### ISSUE THREAD

**Issue by textloop** [cceh/c-salt_dicts_schema#15]
Lieber @fmondaca und @fxru, 

die Monier-Williams-TEI-Dateien in 

https://github.com/cceh/c-salt_sanskrit_data/tree/master/sa_en/mw/split

validieren jetzt fehlerfrei mit 

https://github.com/cceh/c-salt_dicts_schema/blob/master/common/csalt.rng.

Es waren zwei kleiner Anpassungen nötig, vgl:

https://github.com/cceh/c-salt_dicts_schema/issues/13

https://github.com/cceh/c-salt_dicts_schema/issues/14

HINWEIS:
Validiert man hingegen über das tei_all Standardschema bekommt man Fehlermeldungen zum nicht RFC 3066 konformen Wert in @xml:lang von` <hyph ana="key2">` Der von uns im CSALT-Schema ergänzte Wert `san-Latn-x-SLP1-headword2` bezeugt, dass in den alten originalen Monierdaten der Wert in key2 in einem Mischnotation (Transliteration)  angegeben war. Da können wir also nicht so einfach etwas dran ändern und wir müssen es so weiter mitführen. 

Dies Issue dient nur der Kenntnisnahme und kann dann geschlossen werden.

**Comment by fxru** [comment]
Technisch wäre wohl auch `sa-Latn-x-SLP1-headword2` korrekter, aber wahrscheinlich stört sich die Validierung an dem ganzen BCP 47 tag (https://tools.ietf.org/html/bcp470). Wobei RFC 3066 doppelt obsolet ist: BCP 47 “replaces [RFC4646] (which obsoleted [RFC3066] ...)”.

Technisch ist es in beiden so, dass man den ISO 639-1 code verwenden muss (hier `sa`) wenn die Sprache sowohl einen ISO 639-1 und ISO 639-3 (und/oder ISO 639-2) code hat.

> When languages have both an ISO 639-1 two-character code and a three-
   character code (assigned by ISO 639-2, ISO 639-3, or ISO 639-5), only
   the ISO 639-1 two-character code is defined in the IANA registry.

**Comment by fxru** [comment]
Nachtrag: Kann es sein, dass sich die Validierung nur an der Präsenz der `2` in `san-Latn-x-SLP1-headword2` stört?

**Comment by textloop** [comment]
Super, @fxru, das ist die Lösung! Ich hatte das vorher gar nicht hinterfragt. 

Lösung: ich ersetze also alle 

`<hyph ana="key2" xml:lang="san-Latn-x-SLP1-headword2">`

 durch

`<hyph ana="key2" xml:lang="san-Latn-x-SLP1-headword">`
